### ISSUE TITLE
Curious code

### ISSUE THREAD

**Issue by ladlestein** [mesos/myriad#30]
I'm running static analysis using Klocwork on Myriad code (as I'm a sales engineer for Klocwork, and always looking for defects that I can use to support a demo). Noticed this odd bit:

    case TASK_RUNNING:
        schedulerState.makeTaskActive(taskId);
        NodeTask task = schedulerState.getTask(taskId);
        break;
    case TASK_FINISHED:

The "task" variable doesn't appear anywhere in the scope of the switch statement, but it looks like it was supposed to mean something at one point. A few revisions ago, the block looked like this:

	case TASK_RUNNING:
		schedulerState.makeTaskActive(taskIdValue);
		NodeTask task = schedulerState.getTask(taskIdValue);
		schedulerState.releaseLock(task.getClusterId());    <--- interesting
		break;
	case TASK_FINISHED:

Investigating further...the call to `releaseLock()` was dropped in 7a81b91ccde7bdd63ef5d87622d85fae6ef98d94 ("Removed cluster level locking as we are only dealing with 1 cluster now"). So that was probably intentional, and probably the assignment to `task` left was by accident...well, there you go.

**Comment by mohitsoni** [comment]
Good catch @ladlestein, assignment to ```task``` was left by accident. I'll go ahead and fix it. Thanks!

**Comment by ladlestein** [comment]
Glad to contribute. I fixed it in a branch, added another commit to close the "yarn-site.xml" left open in TaskUtils, and made a pull request.

**Comment by mohitsoni** [comment]
@ladlestein thanks for bringing it up, really appreciate it. Once you've address my comment I'll merge the changes.
