### ISSUE TITLE
Support custom users in Mesos

### ISSUE THREAD

**Issue by adam-mesos** [mesos/myriad#47]
The YAML already specifies what user to start each NM as, but the TaskFactory sets the CommandInfo user as "root", and the Scheduler sets the FrameworkInfo user as "" (current user). These should be configurable too, and should not force root.

**Comment by bgulla** [comment]
I have begun working on this.

**Comment by adam-mesos** [comment]
Initial patch from everpeace at https://github.com/mesos/myriad/pull/52

**Comment by adam-mesos** [comment]
Resolved by #83
