### ISSUE TITLE
myriad flexup can crash mesos-slave

### ISSUE THREAD

**Issue by klucar** [mesos/myriad#59]
This hasn't been replicated on a cluster yet. Locally, if a myriad flexup request asks for too many resources, the mesos-slave process crashes and myriad produces no error messages.

**Comment by smarella** [comment]
Does this happen when you try to run Myriad inside Vagrant? Or on a single node Mesos cluster ?

**Comment by klucar** [comment]
it was a single node mesos cluster that was a CentOS VM. I'm working on
getting the vagrant version up.

**Comment by smarella** [comment]
Thanks. Couple of more questions:
1. What are the resource capacities of the mesos-slave as shown on the
mesos-master UI?
2. Does Myriad(ResourceManager) log indicate that it accepted a mesos offer
to launch a NM task?

LOGGER.info("Launching task: {} using offer: {}", task.getTaskId().getValue(),
offer.getId());

Santosh

**Comment by klucar** [comment]
I haven't been able to reproduce this. It seems like it was a dev environment setup issue. I got a new dev machine and haven't had any problems with the included Vagrant single node VM.
